name = 'yinnlimnascloud'
main = "src/worker-vless.js"
compatibility_date = "2026-06-20"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = "92055b9c78e444bba0d2e3f90b4ef03c"				#KV数据库id
